domain: example.com

server:
  database_url: sqlite://./tinyap.db
  host: 127.0.0.1
  port: 8080

metadata:
  instance_name: TinyAP
  instance_description: micro-blogging software built on ActivityPub, part of the Fediverse.<br>NoJS, Fast, Lightweight.<br>More info on <a href="https://github.com/izkluxcvy/tinyap">git repo</a>

config:
  max_note_chars: 2000
  deliver_queue_size: 10
  token_ttl_days: 90

web_config:
  allow_signup: true
  max_sessions_per_user: 10
  max_timeline_items: 50
  timezone: Asia/Tokyo