domain: example.com

# Required for tls feature
tls:
  cert_path: ./server.crt
  key_path: ./server.key

server:
  database_url: sqlite://./tinyap.db
  # database_url: postgresql://user:password@localhost/tinyap
  host: 127.0.0.1
  port: 8080

metadata:
  instance_name: TinyAP
  instance_description: micro-blogging software built on ActivityPub, part of the Fediverse.<br>NoJS, Fast, Lightweight.<br>More info on <a href="https://github.com/izkluxcvy/tinyap">git repo</a>

config:
  max_note_chars: 2000
  deliver_queue_size: 10
  token_ttl_days: 90

# Required for web feature
web_config:
  # temoplates and static directory
  web_dir: ./
  allow_signup: true
  max_sessions_per_user: 10
  max_timeline_items: 30
  timezone: Asia/Tokyo